import type { Experiment, VisualTimelineStep } from "./types";

const visualTimelines: Record<string, VisualTimelineStep[]> = {
  "co2-preparation": [
    {
      id: "co2-setup",
      phase: "setup",
      title: "准备反应装置",
      instruction: "碳酸钙与稀盐酸分别就位，导气管连接澄清石灰水。",
      observationCue: "先确认生成气体会被导入石灰水，而不是直接闻气体。",
      knowledgeTag: "气体制备",
      scene: {
        vessel: "gas-generator",
        liquidColor: "#dceff3",
        secondaryLiquidColor: "#edf6f6",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "calcium-carbonate",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
    {
      id: "co2-reaction",
      phase: "reaction",
      title: "加入稀盐酸",
      instruction: "稀盐酸接触碳酸钙，试管中开始产生气泡。",
      observationCue: "气泡说明有气体生成，但还不能只凭气泡断定就是 CO2。",
      knowledgeTag: "产生 CO2",
      scene: {
        vessel: "gas-generator",
        liquidColor: "#dceff3",
        secondaryLiquidColor: "#edf6f6",
        bubbleIntensity: "medium",
        turbidity: "clear",
        solid: "calcium-carbonate",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
    {
      id: "co2-test",
      phase: "test",
      title: "通入澄清石灰水",
      instruction: "把生成的气体通入澄清石灰水。",
      observationCue: "石灰水逐渐变浑浊，说明生成 CaCO3 沉淀。",
      knowledgeTag: "CO2 检验",
      scene: {
        vessel: "gas-generator",
        liquidColor: "#dceff3",
        secondaryLiquidColor: "#d8d8cf",
        bubbleIntensity: "soft",
        turbidity: "cloudy",
        solid: "calcium-carbonate",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
    {
      id: "co2-conclusion",
      phase: "conclusion",
      title: "形成实验结论",
      instruction: "把气泡和石灰水浑浊作为两个连续证据。",
      observationCue: "结论不是“有气泡”，而是“生成并检验出 CO2”。",
      knowledgeTag: "证据链",
      scene: {
        vessel: "gas-generator",
        liquidColor: "#dceff3",
        secondaryLiquidColor: "#d8d8cf",
        bubbleIntensity: "none",
        turbidity: "cloudy",
        solid: "calcium-carbonate",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
  ],
  "acid-base-neutralization": [
    {
      id: "neutralization-setup",
      phase: "setup",
      title: "滴入酚酞",
      instruction: "在氢氧化钠溶液中滴入酚酞。",
      observationCue: "碱性环境下酚酞呈粉红色。",
      knowledgeTag: "指示剂",
      scene: {
        vessel: "beaker",
        liquidColor: "#f7a8c4",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "none",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
    {
      id: "neutralization-reaction",
      phase: "reaction",
      title: "逐滴加入盐酸",
      instruction: "边滴加边振荡，观察颜色变化。",
      observationCue: "颜色逐渐变浅，不应期待大量气泡。",
      knowledgeTag: "酸碱中和",
      scene: {
        vessel: "beaker",
        liquidColor: "#f3c6d5",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "none",
        colorChange: "pink-to-clear",
        flame: "none",
        temperature: "warm",
      },
    },
    {
      id: "neutralization-observation",
      phase: "observation",
      title: "接近中性",
      instruction: "继续少量滴加，溶液颜色褪去。",
      observationCue: "无气泡也能发生反应，证据是指示剂颜色变化和放热。",
      knowledgeTag: "误区纠正",
      scene: {
        vessel: "beaker",
        liquidColor: "#f3f4f2",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "none",
        colorChange: "fade",
        flame: "none",
        temperature: "warm",
      },
    },
    {
      id: "neutralization-conclusion",
      phase: "conclusion",
      title: "形成实验结论",
      instruction: "用 H+ 与 OH- 生成水解释颜色变化。",
      observationCue: "酸碱中和的核心证据不是气体，而是酸碱性改变。",
      knowledgeTag: "离子反应",
      scene: {
        vessel: "beaker",
        liquidColor: "#f3f4f2",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "none",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
  ],
  "iron-copper-sulfate": [
    {
      id: "iron-setup",
      phase: "setup",
      title: "处理铁钉",
      instruction: "打磨铁钉后放入硫酸铜溶液。",
      observationCue: "洁净铁表面更容易观察生成物。",
      knowledgeTag: "金属活动性",
      scene: {
        vessel: "beaker",
        liquidColor: "#62b7d8",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "iron-nail",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
    {
      id: "iron-reaction",
      phase: "reaction",
      title: "发生置换反应",
      instruction: "铁与硫酸铜溶液接触。",
      observationCue: "铁表面开始出现红色物质。",
      knowledgeTag: "铜析出",
      scene: {
        vessel: "beaker",
        liquidColor: "#73bfd9",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "copper-coating",
        colorChange: "blue-fade",
        flame: "none",
        temperature: "normal",
      },
    },
    {
      id: "iron-observation",
      phase: "observation",
      title: "观察颜色变化",
      instruction: "继续观察铁表面和溶液颜色。",
      observationCue: "红色铜附着在铁表面，蓝色溶液变浅。",
      knowledgeTag: "置换证据",
      scene: {
        vessel: "beaker",
        liquidColor: "#a7d5d6",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "copper-coating",
        colorChange: "blue-fade",
        flame: "none",
        temperature: "normal",
      },
    },
    {
      id: "iron-conclusion",
      phase: "conclusion",
      title: "形成实验结论",
      instruction: "用金属活动性解释置换反应。",
      observationCue: "红色物质是铜，不是铁锈。",
      knowledgeTag: "材料联系",
      scene: {
        vessel: "beaker",
        liquidColor: "#a7d5d6",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "copper-coating",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
  ],
  "oxygen-preparation": [
    {
      id: "oxygen-setup",
      phase: "setup",
      title: "加入二氧化锰",
      instruction: "向过氧化氢溶液中加入少量二氧化锰。",
      observationCue: "二氧化锰是催化剂，不是生成物。",
      knowledgeTag: "催化剂",
      scene: {
        vessel: "test-tube",
        liquidColor: "#e9f3fb",
        bubbleIntensity: "soft",
        turbidity: "clear",
        solid: "manganese-dioxide",
        colorChange: "none",
        flame: "ember",
        temperature: "normal",
      },
    },
    {
      id: "oxygen-reaction",
      phase: "reaction",
      title: "快速产生气泡",
      instruction: "过氧化氢分解，试管中出现大量气泡。",
      observationCue: "气泡说明有氧气生成，但要用木条进一步检验。",
      knowledgeTag: "生成 O2",
      scene: {
        vessel: "test-tube",
        liquidColor: "#eef8ff",
        bubbleIntensity: "strong",
        turbidity: "clear",
        solid: "manganese-dioxide",
        colorChange: "none",
        flame: "ember",
        temperature: "normal",
      },
    },
    {
      id: "oxygen-test",
      phase: "test",
      title: "带火星木条复燃",
      instruction: "将带火星木条伸入集气瓶。",
      observationCue: "木条复燃说明氧气支持燃烧。",
      knowledgeTag: "O2 检验",
      scene: {
        vessel: "test-tube",
        liquidColor: "#eef8ff",
        bubbleIntensity: "medium",
        turbidity: "clear",
        solid: "manganese-dioxide",
        colorChange: "none",
        flame: "rekindled",
        temperature: "normal",
      },
    },
    {
      id: "oxygen-conclusion",
      phase: "conclusion",
      title: "形成实验结论",
      instruction: "把气泡和木条复燃连接成证据链。",
      observationCue: "关键结论是制取并检验出氧气。",
      knowledgeTag: "证据链",
      scene: {
        vessel: "test-tube",
        liquidColor: "#eef8ff",
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "manganese-dioxide",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    },
  ],
};

export function createVisualTimeline(experiment: Experiment): VisualTimelineStep[] {
  return (
    visualTimelines[experiment.id] ??
    experiment.steps.map((step, index) => ({
      id: `${experiment.id}-${index}`,
      phase: index === 0 ? "setup" : index === experiment.steps.length - 1 ? "conclusion" : "observation",
      title: step.title,
      instruction: step.detail,
      observationCue: experiment.observations[index]?.label ?? experiment.conclusion,
      knowledgeTag: experiment.observations[index]?.kind ?? "实验观察",
      scene: {
        vessel: "test-tube",
        liquidColor: experiment.visual.liquidAfter,
        bubbleIntensity: "none",
        turbidity: "clear",
        solid: "none",
        colorChange: "none",
        flame: "none",
        temperature: "normal",
      },
    }))
  );
}
